name: Main PR Label

on:
  pull_request:
    branches: [main]
    types: [reopened, labeled, unlabeled]

jobs:
  check-labels:
    name: 'Check PR Labels'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mheap/github-action-required-labels@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: exactly
          count: 1
          labels: 'major, minor, patch'