name: Main PR Open

on:
  pull_request:
    branches: [main]
    types: [opened, reopened]

jobs:
  add-comment:
    name: 'Add Comment'
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v2
        with:
          message: Please set a versioning label of either `major`, `minor`, or `patch` to the pull request.
          repo-token: ${{ secrets.GITHUB_TOKEN }}