name: Push

on:
  push:
    branches-ignore: [main]

jobs:
  build-contracts:
    name: Build Contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.4.2'
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: yarn compile

  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.4.2'
          registry-url: https://registry.npmjs.org/
      - uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - run: pip install mkdocs mkdocs-material mkdocs-minify-plugin
      - run: yarn build-docs

  lint-contracts:
    name: Lint Contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.4.2'
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: yarn lint
      - run: yarn format

  test-contracts:
    name: Test Contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.4.2'
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: yarn test